dist: xenial
os: linux
language: node_js
node_js:
  - lts/*
addons:
  chrome: stable
services:
  - xvfb
cache:
  directories:
    - node_modules
install: npm install --legacy-peer-deps
after_success: npm run coverage
