dist: trusty
sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=8.12.0 DBUS_SESSION_BUS_ADDRESS=/dev/null
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@latest
  - npm install
script:
  - npm test
  - cat test/unit/coverage/lcov.info | node_modules/.bin/coveralls
