export GeomPoint from './point'
export GeomLineString from './line-string'
export GeomPolygon from './polygon'
export GeomMultiPoint from './multi-point'
export GeomMultiLineString from './multi-line-string'
export GeomMultiPolygon from './multi-polygon'
